version: '3.8'

services:
  elqkit:
    build: .
    container_name: elqkit
    ports:
      - "8847:8847"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - PORT=8847
      - SECRET_KEY=dev-key-change-for-production
    volumes:
      # Mount source code for development (comment out for production)
      - .:/app
      - /app/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8847/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: elqkit-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - elqkit
  #   restart: unless-stopped

networks:
  default:
    name: elqkit-network